"""Deterministic final research report generation from pipeline outputs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from mrrp.reporting.formatting import (
    format_comparison_csv,
    format_named_metric,
    format_number,
)


@dataclass(frozen=True)
class ResearchReportInputs:
    """Structured inputs for the final research report."""

    title: str
    abstract: str
    research_question: str
    dataset_description: str
    data_quality_summary: str
    feature_engineering_summary: str
    risk_metrics_summary: str
    model_methodology: str
    model_comparison_markdown: str
    stress_tests_markdown: str
    backtest_methodology: str
    results_markdown: str
    failure_analysis: str
    limitations: tuple[str, ...]
    future_work: tuple[str, ...]
    reproduction_steps: tuple[str, ...]


def render_research_report(inputs: ResearchReportInputs) -> str:
    """Render the final Markdown research report."""
    limitations = "\n".join(f"- {item}" for item in inputs.limitations)
    future = "\n".join(f"- {item}" for item in inputs.future_work)
    repro = "\n".join(
        f"{idx}. {item}" for idx, item in enumerate(inputs.reproduction_steps, start=1)
    )
    return f"""# {inputs.title}

## Abstract

{inputs.abstract}

## Research question

{inputs.research_question}

## Dataset and ETF proxies

{inputs.dataset_description}

## Data quality

{inputs.data_quality_summary}

## Feature engineering

{inputs.feature_engineering_summary}

## Risk metrics

{inputs.risk_metrics_summary}

## Model methodology

{inputs.model_methodology}

## Model comparison

{inputs.model_comparison_markdown}

## Stress tests

{inputs.stress_tests_markdown}

## Backtest methodology

{inputs.backtest_methodology}

## Results

{inputs.results_markdown}

## Failure analysis

{inputs.failure_analysis}

## Limitations

{limitations}

## Future work

{future}

## Reproduction instructions

{repro}

---
Generated from actual platform outputs. Not investment advice. Not a prediction system.
"""


def default_report_inputs_from_artifacts(
    *,
    comparison_csv: str | None = None,
    stress_summary: Mapping[str, float] | None = None,
    backtest_summary: Mapping[str, float] | None = None,
) -> ResearchReportInputs:
    """Build a conservative report skeleton, inserting tables only when present."""
    comparison_md = "_Model comparison artifact not available._"
    if comparison_csv and Path(comparison_csv).exists():
        text = Path(comparison_csv).read_text(encoding="utf-8").strip()
        comparison_md = (
            "Comparison table generated by the model pipeline:\n\n"
            "```csv\n"
            f"{format_comparison_csv(text)}\n"
            "```\n\n"
            "Metrics are family-aware and are not all directly comparable."
        )

    stress_md = "_Stress results not supplied._"
    if stress_summary:
        lines = "\n".join(
            f"- {key}: {format_number(value, percent=True)}"
            for key, value in stress_summary.items()
        )
        stress_md = lines

    results_md = "_Results pending full pipeline artifacts._"
    if backtest_summary:
        lines = "\n".join(
            f"- {key}: {format_named_metric(key, value)}"
            for key, value in backtest_summary.items()
        )
        results_md = (
            "Backtest metrics from the configured research run:\n\n"
            f"{lines}\n\n"
            "These are historical simulations only."
        )

    return ResearchReportInputs(
        title="Market Regime and Portfolio Risk Platform — Final Research Report",
        abstract=(
            "This report documents a leakage-aware portfolio risk and regime-analysis "
            "platform spanning data ingestion, feature engineering, interpretable and "
            "probabilistic regime models, stress testing, and no-look-ahead backtesting. "
            "The platform is designed for risk research, not return prediction."
        ),
        research_question=(
            "How can portfolio risk, market regimes, stress exposures, and simple "
            "risk-aware allocation rules be measured in a reproducible, "
            "look-ahead-resistant research platform?"
        ),
        dataset_description=(
            "The research universe uses liquid ETF proxies (for example SPY, QQQ, "
            "XIU.TO, EFA, EEM, and sector ETFs such as XLK) configured in "
            "`configs/default_universe.yaml` and `configs/sample_portfolio.yaml`. "
            "These are market proxies, not a complete institutional security master."
        ),
        data_quality_summary=(
            "Data quality checks cover missing values, duplicate dates, alignment, "
            "and freshness. Free ETF history may be shorter than requested stress "
            "windows; coverage warnings are required in those cases."
        ),
        feature_engineering_summary=(
            "Week 5 regime features use trailing volatility, correlation, drawdown, "
            "and momentum signals. Scalers are fit on the training period only."
        ),
        risk_metrics_summary=(
            "The risk engine provides returns, volatility, drawdown, Sharpe/Sortino/"
            "Calmar, VaR/CVaR, beta, correlation, concentration, and risk contribution."
        ),
        model_methodology=(
            "Regime models include an interpretable threshold baseline, KMeans, GMM, "
            "GaussianHMM, and ruptures change-point detectors. Models fit on training "
            "data only; economic labels are derived from training-period state statistics."
        ),
        model_comparison_markdown=comparison_md,
        stress_tests_markdown=stress_md,
        backtest_methodology=(
            "Backtests distinguish signal, decision, execution, and return realization "
            "dates; signals are shifted to prevent same-close execution; transaction "
            "costs and turnover are accounted for; future mutations must not alter "
            "earlier positions."
        ),
        results_markdown=results_md,
        failure_analysis=(
            "1) Regime-label instability across seeds/specs; economic relabeling helps "
            "but does not create unique true states. "
            "2) State-identification ambiguity without a unique causal map. "
            "3) Window sensitivity of trailing features (21d/63d/252d). "
            "4) Number-of-state sensitivity in interpretability and duration stats. "
            "5) Non-stationarity of risk regimes after the training window. "
            "6) ETF proxy limitations for sector/region/factor exposures. "
            "7) Free-data history gaps and revisions. "
            "8) Crisis correlation breakdown versus calm-sample diversification. "
            "9) VaR/CVaR sample dependence and unseen-tail limits. "
            "10) Simplified proportional transaction costs. "
            "11) Bull-market underperformance of defensive/de-risking rules. "
            "12) Backtest overfitting and model-selection bias if rules are chosen "
            "after seeing results."
        ),
        limitations=(
            "Not a stock-prediction system.",
            "Not financial advice.",
            "ETF data quality and history constraints.",
            "Model metrics are not universally comparable across families.",
            "Transaction-cost model is proportional and simplified.",
        ),
        future_work=(
            "Richer factor risk models beyond ETF sector proxies.",
            "Bayesian or online regime filters with strict latency assumptions.",
            "Broker-aware cost models and capacity constraints.",
        ),
        reproduction_steps=(
            "uv sync",
            "make data",
            "make features && make feature-check",
            "make models && make model-check",
            "make stress",
            "make backtest",
            "make report",
            "make check",
        ),
    )


def write_research_report(path: str, markdown: str) -> None:
    """Persist the research report Markdown."""
    Path(path).write_text(
        markdown if markdown.endswith("\n") else markdown + "\n",
        encoding="utf-8",
    )


def architecture_mermaid() -> str:
    """Return a version-controllable Mermaid architecture diagram."""
    return """```mermaid
flowchart TD
  configs[configs YAML] --> data[mrrp.data]
  data --> features[mrrp.features]
  data --> portfolio[mrrp.portfolio]
  portfolio --> risk[mrrp.risk]
  features --> models[mrrp.models]
  risk --> stress[mrrp.risk.stress]
  models --> backtest[mrrp.backtest]
  features --> backtest
  portfolio --> backtest
  risk --> reporting[mrrp.reporting]
  models --> reporting
  stress --> reporting
  backtest --> reporting
  portfolio --> dashboard[mrrp.dashboard]
  risk --> dashboard
  features --> dashboard
  models --> dashboard
  stress --> dashboard
  backtest --> dashboard
  reporting --> dashboard
  dashboard --> app[Streamlit app pages]
```"""
